version: '3.7'
services:
  julia:
    build:
      context: julia-opf/
      args:
        - password=${ROOT_PASSWORD}
        - dbpassword=${DEBUG_PASSWORD}
    container_name: julia-opf
    image: julia-opf
    volumes:
      - ./data:/root/data
      - ./src:/root/src
    working_dir: /root/src
    cpuset: "1-3"
    #command: julia --color=yes --check-bounds=yes --inline=yes --depwarn=yes --project=@. -e 'using Pkg; Pkg.test(coverage=true)'
